### ISSUE TITLE
VR을 통한 부동산 매물소개의 한계점

### ISSUE THREAD

**Issue by phs6417** [kookmin-sw/2018-cap1-15#1]
VR을 사용하고자 하는 생각에 

VR이 가장 유용하다고 생각하는 부동산 어플을 만들기로 했다.

하지만 만들다보니 기존의 어플과의 차별점이 특별하지 않고,

색다른 기능을 추가하는데 한계를 느낀다.

새로운 기능을 추가하거나, 기술을 이용하여 만들 주제를 좀 더 생각하고

심하면 주제를 뒤엎어야 할 것 같다.

**Comment by mirjun21** [comment]
VR 기술을 이용한 부동산 매물 소개에서 그치지말고,

사용자가 직접 가구를 임의로 배치해 볼 수있는 기능을 추가하면 좋을 것같다.

VR로 빈 방을 보며, 그 위에 가구를 덧입혀 볼수 있는 형식으로

기존의 어플과의 차별점을 얻을수 있을것 같다.

추가적인 문제점이나, 더해야할 기능들에 대해 좀 더 연구해야 할 필요성이 있다.

**Comment by mountrivers** [comment]
VR 로 가구를 덧입히기에 가장 문제되는점은 
우리가 이미지를 인식해서 바닥의 위치를 인식 하기 힘들다는점과, 
입체적으로 3d 빌드 된  구조 형태가 아니라 사진을 vr로 만드는 것이라서 거리감을 잴 수 없음 으로 문제가 있어보임. 
거리감은 skybox 를 사용하는대신 정육면체에 6면을 도입하는 방식으로 비슷하게 만들 수 있긴 하지만 확실히 skybox 를 사용하는것에 비해 light 에 그늘 생기는 것 등 사용이 힘들고 부자연스러운티가 많이남..
만약 한다면 바닥 4귀퉁이 찍어야 할듯
