### ISSUE TITLE
전시물(공룡) 세부 내용전달 방법

### ISSUE THREAD

**Issue by mirjun21** [kookmin-sw/2018-cap1-15#11]
기존에 구상하던 방식으로는 특정 화면 어딘가를 응시하면

해당 정보가 글 형태로 보여지는 것을 생각했었는데,

아무래도 공룡 전시물의 경우 생동감이 중요할것같아

애니메이션과 함께 공룡 울음소리와 해당 공룡의 세부 정보도 음성으로 지원하는게 좋을듯

**Comment by mountrivers** [comment]
3d 모델링을 구하는게 관건 만약 모은다면 VR 뿐만아니라 AR방향 확장가능성

**Comment by phs6417** [comment]
울음소리는 생동감을 주는데 도움이 될 거 같네
세부정보를 음성을 통한 전달은 설명이 길어지면 알아듣기 어려울 수 있겠네
음성의 자막이라던가 핵심키워드를 화면에 노출하는 방식은 어떨까?

**Comment by mirjun21** [comment]
자막은 자칫하면 뷰가 지저분해질수 있을거같음

간단한 소개 창을 띄우고 핵심 정보만 뷰에 노출시키고

울음소리 끝난뒤에 자연스럽게 설명이 이어지는건 어떨까
