### ISSUE TITLE
vr모두중 2d로 전환해도 버튼 작동 안함. 

### ISSUE THREAD

**Issue by mountrivers** [kookmin-sw/2018-cap1-15#19]
뭔가 대체 방안이 필요함 
canvas에 박은 버튼만 안되는건지
오브젝트 에 버튼 박아도 안되는건지 확인필요

**Comment by phs6417** [comment]
UI->버튼은 핸드폰 UI 특정 위치에 고정이니깐 캔버스에 박아야 하지 않을까
버튼 위치를 바꿀려면 오브젝트로 만들고 위치 고정은 버튼으로 만들테니
어떤 식으로 구현할지는 좀 더 생각해보자
