### ISSUE TITLE
VR 기능에 전망 뷰 관련 드론을 이용하는건 어떨까

### ISSUE THREAD

**Issue by mountrivers** [kookmin-sw/2018-cap1-15#6]
VR로 방 뿐만 아니라 주변 뷰를 봐도 좋을거 같은데

물론 전망이 좋은 집만 있는 건 아니지만 

한강근처라던가 전망이 좋은 곳이라면 

드론 이용해서 뷰를 찍거나

아니면 창문에서 제한적인 뷰를 제공해도 좋을거 같다고생각함

**Comment by mirjun21** [comment]
아이디어 자체는 좋은 아이디어라고 생각

비주얼적면으로 어떻게 제공할건지에 대해 생각해봐야할듯
