### ISSUE TITLE
바닥을 인식시키는 방법 제안사항

### ISSUE THREAD

**Issue by mirjun21** [kookmin-sw/2018-cap1-15#9]
Sky box를 이용하여 평면2D사진을 6분할 하여 사용하는 방향으로 생각중이니,

천장면과 하단부면을 제외한 후 전후좌우면만으로 VR화면을 구성한 후에,

빈칸으로 구성된 천장면과 바닥면의 좌표값을 얻어내어 가구배치 시뮬레이션에 이용할수 있지않을까?

오차범위는 어느정도 있을거라고 예상되긴함

**Comment by mountrivers** [comment]
스카이박스는 거리를 상당히 두기때문에 스카이박스로 하기는 힘들듯
